name: Fetch US symbol list

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 22 * * 1-5'    # every weekday at 22:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download NASDAQ list via FTP
        run: |
          curl -sL ftp://ftp.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt \
            -o nasdaqlisted.txt

      - name: Download NYSE/AMEX list via FTP
        run: |
          curl -sL ftp://ftp.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt \
            -o otherlisted.txt

      - name: Commit updated symbol files
        run: |
          git config user.name  symbol-bot
          git config user.email symbol-bot@users.noreply.github.com
          git add nasdaqlisted.txt otherlisted.txt
          git commit -m "auto-update symbols $(date -u +%F)" || echo "no change"
          git push
